Mmuustafa/increaselogosize
acm-ucr/highlander-gloves-website pull request #105
Opened 2024-10-27 02:11 UTC by mmuustafa

![Image 10-26-24 at 7 08 PM](https://github.com/user-attachments/assets/ba14ab38-15be-4ebb-bbc3-9f6ae3b3539d)

2024-10-28 04:02 UTC, SafeDuck requested changes

2024-10-28 04:02 UTC, SafeDuck commented on src/components/Navigation.tsx
It seems like the text is no longer centered on the y-axis of the Navigation component. Could you fix that?

2024-10-29 21:37 UTC, mmuustafa commented on src/components/Navigation.tsx
fixed with a top margin

2024-11-01 06:43 UTC, SafeDuck approved these changes

2024-11-01 06:43 UTC, merged