added links to socials when clicked
acm-ucr/highlander-gloves-website pull request #190
Opened 2024-11-26 00:40 UTC by mmuustafa

2024-11-27 02:07 UTC, SafeDuck requested changes

2024-11-27 02:07 UTC, SafeDuck commented on src/components/home/Socials.tsx
> +      <a
Don't use `a` tags. Use `Link` component from `next/link`
Check footer for an example

2024-11-30 22:39 UTC, mmuustafa commented
Should be good now hopefully! Lmk if you need any other changes

2024-11-30 23:19 UTC, SafeDuck approved these changes

2024-11-30 23:19 UTC, merged