reverted get started files -- header component
acm-ucr/highlander-gloves-website pull request #22
Opened 2024-10-04 07:12 UTC by kayliezhao

added header component & used for the how to get started
![image](https://github.com/user-attachments/assets/4ed00340-04c5-46a9-ac29-a764164fd18b)

2024-10-06 05:47 UTC, SafeDuck requested changes

2024-10-06 05:47 UTC, SafeDuck commented on src/app/home/gets-started.js
> +const Home = () => {
The folder and files shouldn't be created. Please remove. Next meeting will explain why with next.js routing system.

2024-10-06 05:47 UTC, SafeDuck commented on src/components/Header.tsx
> +      className={`w-1/8 flex flex-row border-b-4 border-t-4 border-white p-2 pl-[5%] pr-[5%] text-3xl text-white ${props.position === "left" ? "border-r-4" : "border-l-4"}`}
Are you sure `w-1/8` is a class in tailwind? 
Hover over it in vscode (tailwind intellisense)

2024-10-06 06:04 UTC, SafeDuck commented on src/components/Header.tsx
> +      className={`w-1/8 flex flex-row border-b-4 border-t-4 border-white p-2 pl-[5%] pr-[5%] text-3xl text-white ${props.position === "left" ? "border-r-4" : "border-l-4"}`}
Add font too.

2024-10-07 05:04 UTC, kayliezhao commented
deleted the extra file, changed font
<img width="426" alt="image" src="https://github.com/user-attachments/assets/95be2740-8180-44a4-9b98-37242911ce83">

2024-10-07 21:10 UTC, SafeDuck requested changes

2024-10-07 21:10 UTC, SafeDuck commented on src/app/home/gets-started.js
> +  return <GetStarted />;
delete this folder and files

2024-10-07 21:10 UTC, SafeDuck commented on src/components/home/GetStarted.tsx
> +        <Header position="left" title={props.txt1} />
Revert this file back to it's original state

2024-10-08 00:52 UTC, kayliezhao commented
reverted get started

2024-10-08 01:45 UTC, SafeDuck approved these changes

2024-10-08 01:45 UTC, merged