Create button component
acm-ucr/highlander-gloves-website pull request #23
Opened 2024-10-05 01:31 UTC by aldriebarcena

<img width="459" alt="Screenshot 2024-10-04 at 6 25 32 PM" src="https://github.com/user-attachments/assets/a5ef4175-f1b5-41bd-aaad-5f8346df99eb">

2024-10-06 06:25 UTC, SafeDuck requested changes

2024-10-06 06:25 UTC, SafeDuck commented on src/components/Button.tsx
> +    <div className="box-border flex h-[82px] w-[392px] items-center justify-center rounded-[50px] border-[5px] border-hlg-red-300 bg-hlg-red-200 font-archivo-black text-[36px]">
1. Remove the height and don't hard code width, it should be possible to make the button using only padding and width. I recommend `w-1/6 py-2`
2. Don't hard code the rounded, use a class provided from tailwind like `rounded-full` or `rounded-lg`
3. Don't hard code the `text` use a tailwind class like `text-lg` or `text-2xl` etc.
4. Issue states to use `Link` from `next/link` The outside `div` should be a `Link`

2024-10-06 22:01 UTC, aldriebarcena commented
<img width="281" alt="Screenshot 2024-10-06 at 3 00 58 PM" src="https://github.com/user-attachments/assets/0201743a-ac9b-40c4-a322-54772b834705">

2024-10-06 23:45 UTC, SafeDuck requested changes

2024-10-06 23:45 UTC, SafeDuck commented on src/components/Button.tsx
> +        <Link href={props.link} className="relative text-white">
Use the `Link` Component on the outer most div on line 6
This way the whole button is clickable, not just the text

2024-10-07 01:39 UTC, SafeDuck approved these changes

2024-10-07 01:39 UTC, merged