fixed photo component for flexibility, added get started section
acm-ucr/highlander-gloves-website pull request #50
Opened 2024-10-13 07:57 UTC by kayliezhao

fixed the photo component for sizing issues , added the get started section
<img width="934" alt="image" src="https://github.com/user-attachments/assets/caad8b0f-271d-480d-b64c-98dff93e5d17">

2024-10-13 20:07 UTC, SafeDuck requested changes

2024-10-13 20:07 UTC, SafeDuck commented on src/components/Photo.tsx
>    width: number;
let's make width a string. In particular a tailwind class. 
For example `w-1/2` or `w-1/4`

2024-10-13 20:07 UTC, SafeDuck commented on src/components/Photo.tsx
>          width={width}
Remove the `width` prop from the Image component.
Use a tailwind class instead, aka the string `width` from the props

2024-10-13 20:07 UTC, SafeDuck commented on src/components/home/GetStarted.tsx
> +            <div className="ml-11 flex w-[200%] translate-x-[-30%] justify-center p-11">
the `translate` shouldn't be needed. This component can be done with `flex` alone

2024-10-13 20:07 UTC, SafeDuck commented on src/components/home/GetStarted.tsx
> +          <div className="ml-11 pr-32">
Too much hard coding padding. 
Use `flex` properties instead. Refer to example:
![image](https://github.com/user-attachments/assets/387d6339-476a-4d94-b06d-2cacfad93400)

Essentially, we want reliance on padding and more reliance on `flex` alone

2024-10-14 03:26 UTC, kayliezhao commented
removed width prop, used less padding, adjusted button component so i dont have to translate when i resize the button width
<img width="899" alt="image" src="https://github.com/user-attachments/assets/d4b42b3d-02d2-41b5-aeba-ebaa51fea19f">

2024-10-15 23:09 UTC, SafeDuck approved these changes

2024-10-15 23:09 UTC, merged