added top portion of news page
acm-ucr/highlander-gloves-website pull request #77
Opened 2024-10-18 19:51 UTC by kayliezhao

is this how we are supposed to work on the same branch
added top portion of news page 
<img width="944" alt="image" src="https://github.com/user-attachments/assets/dcc46d37-65c6-41d7-bf31-c839f1bd75bf">

2024-10-20 06:45 UTC, SafeDuck requested changes

2024-10-20 06:45 UTC, SafeDuck commented on src/components/home/Times.jsx
This file isn't part of the issue

2024-10-20 06:45 UTC, SafeDuck commented on src/components/Header.tsx
Why were changes made to this file?

2024-10-20 06:45 UTC, SafeDuck commented on public/news/NewsPerez.webp
Please make sure all images are less than 200 kb
https://tinypng.com/

2024-10-20 07:17 UTC, shirleyduong commented on src/components/home/Times.jsx
Not really sure how this file came back up since I deleted it before, sorry! I just deleted it

2024-10-21 01:21 UTC, SafeDuck requested changes

2024-10-21 01:21 UTC, SafeDuck commented on src/components/Photo.jsx
> +  return <div>Photo</div>;
Where did this file come from?

2024-10-21 06:06 UTC, SafeDuck requested changes

2024-10-21 06:06 UTC, SafeDuck commented on src/app/news/page.tsx
> +          <a
Use `Link` component from next instead of `a` tag

2024-10-21 22:27 UTC, kayliezhao commented
changed to use Link from next.js
<img width="740" alt="image" src="https://github.com/user-attachments/assets/08247174-d070-41f7-9694-282a52090572">

2024-10-22 02:02 UTC, SafeDuck approved these changes

2024-10-22 02:02 UTC, merged